In [1]:
import pandas as pd

In [3]:
mapc_data = pd.read_csv("mapc.ma_parcels_metrofuture.csv")
mapc_data

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (6,7,14,17,18,28,29,34) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,objectid,mapc_id,muni_id,muni,parloc_id,poly_typ,map_num,mappar_id,loc_id_cnt,land_value,...,landv_pac,bldgv_psf,totv_pac,bldlnd_rat,sqm_imperv,sqm_bldg,sqm_pave,realesttyp,temp,shape
0,1024990,1793971,165,Malden,F_776190_2978608,FEE,083,83-401-102,1.0,126700.0,...,1.827386e+06,104.211747,5.717253e+06,2.128650,200.785689,137.674874,63.110815,6.0,NaN,5400000009000000080010006A6900003C015801010000...
1,1024991,1793972,165,Malden,F_775239_2978598,FEE,081,81-368-817,1.0,134100.0,...,1.351725e+06,126.996587,5.205300e+06,2.850858,274.586732,162.669607,111.917125,2.0,NaN,4200000006000000080010006A6900002A015801010000...
2,1024992,1793973,165,Malden,F_772696_2978619,FEE,065,65-311-113,1.0,122700.0,...,1.971249e+06,108.932854,4.890369e+06,1.480848,210.810312,79.619434,131.190879,2.0,NaN,4200000006000000080010006A6900002A015801010000...
3,1024993,1793974,165,Malden,F_775846_2978591,FEE,083,83-366-617,1.0,147600.0,...,9.558940e+05,87.556482,2.587261e+06,1.706640,259.279507,138.767136,120.512371,2.0,NaN,4E00000008000000080010006A69000036015801010000...
4,1024994,1793975,165,Malden,F_773556_2978611,FEE,077,77-372-204,1.0,127300.0,...,1.816643e+06,128.821726,6.013617e+06,2.310291,241.963377,116.325032,125.638345,2.0,NaN,3C00000005000000080010006A69000024015801010000...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274940,1024985,1793966,165,Malden,F_773695_2978615,FEE,77,77-372-208,1.0,124800.0,...,1.933750e+06,110.719814,6.366811e+06,2.292468,215.068744,130.951045,84.117699,2.0,NaN,4700000007000000080010006A6900002F015801010000...
1274941,1024986,1793967,165,Malden,F_770409_2978617,FEE,38,38-207-710,1.0,124000.0,...,1.196214e+06,82.300319,2.438733e+06,1.038710,221.971897,99.119456,122.852441,1.0,NaN,5A0000000B000000080010006A69000082015801010000...
1274942,1024987,1793968,165,Malden,F_774044_2978598,FEE,82,82-380-9,1.0,135100.0,...,1.345761e+06,115.096439,4.542317e+06,2.375278,320.295866,168.038193,152.257673,2.0,NaN,4200000006000000080010006A6900002A015801010000...
1274943,1024988,1793969,165,Malden,F_774735_2978601,FEE,81,81-385-511,1.0,132300.0,...,1.470200e+06,89.282900,4.046107e+06,1.752079,223.791689,169.687216,54.104474,2.0,NaN,4200000006000000080010006A6900002A015801010000...
1274944,1024989,1793970,165,Malden,F_776423_2978611,FEE,83,83-400-7,1.0,123800.0,...,2.159648e+06,97.454997,4.898459e+06,1.268174,193.137711,73.759930,119.377781,1.0,NaN,4600000007000000080010006A6900002E015801010000...

In [4]:
# 1. filter by using type of parcel which equals to FEE or TAX
mapc_fee_tax = mapc_data[(mapc_data['poly_typ'] == 'FEE') | (mapc_data['poly_typ'] == 'TAX')]
mapc_fee_tax

,objectid,mapc_id,muni_id,muni,parloc_id,poly_typ,map_num,mappar_id,loc_id_cnt,land_value,...,landv_pac,bldgv_psf,totv_pac,bldlnd_rat,sqm_imperv,sqm_bldg,sqm_pave,realesttyp,temp,shape
0,1024990,1793971,165,Malden,F_776190_2978608,FEE,083,83-401-102,1.0,126700.0,...,1.827386e+06,104.211747,5.717253e+06,2.128650,200.785689,137.674874,63.110815,6.0,NaN,5400000009000000080010006A6900003C015801010000...
1,1024991,1793972,165,Malden,F_775239_2978598,FEE,081,81-368-817,1.0,134100.0,...,1.351725e+06,126.996587,5.205300e+06,2.850858,274.586732,162.669607,111.917125,2.0,NaN,4200000006000000080010006A6900002A015801010000...
2,1024992,1793973,165,Malden,F_772696_2978619,FEE,065,65-311-113,1.0,122700.0,...,1.971249e+06,108.932854,4.890369e+06,1.480848,210.810312,79.619434,131.190879,2.0,NaN,4200000006000000080010006A6900002A015801010000...
3,1024993,1793974,165,Malden,F_775846_2978591,FEE,083,83-366-617,1.0,147600.0,...,9.558940e+05,87.556482,2.587261e+06,1.706640,259.279507,138.767136,120.512371,2.0,NaN,4E00000008000000080010006A69000036015801010000...
4,1024994,1793975,165,Malden,F_773556_2978611,FEE,077,77-372-204,1.0,127300.0,...,1.816643e+06,128.821726,6.013617e+06,2.310291,241.963377,116.325032,125.638345,2.0,NaN,3C00000005000000080010006A69000024015801010000...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274940,1024985,1793966,165,Malden,F_773695_2978615,FEE,77,77-372-208,1.0,124800.0,...,1.933750e+06,110.719814,6.366811e+06,2.292468,215.068744,130.951045,84.117699,2.0,NaN,4700000007000000080010006A6900002F015801010000...
1274941,1024986,1793967,165,Malden,F_770409_2978617,FEE,38,38-207-710,1.0,124000.0,...,1.196214e+06,82.300319,2.438733e+06,1.038710,221.971897,99.119456,122.852441,1.0,NaN,5A0000000B000000080010006A69000082015801010000...
1274942,1024987,1793968,165,Malden,F_774044_2978598,FEE,82,82-380-9,1.0,135100.0,...,1.345761e+06,115.096439,4.542317e+06,2.375278,320.295866,168.038193,152.257673,2.0,NaN,4200000006000000080010006A6900002A015801010000...
1274943,1024988,1793969,165,Malden,F_774735_2978601,FEE,81,81-385-511,1.0,132300.0,...,1.470200e+06,89.282900,4.046107e+06,1.752079,223.791689,169.687216,54.104474,2.0,NaN,4200000006000000080010006A6900002A015801010000...
1274944,1024989,1793970,165,Malden,F_776423_2978611,FEE,83,83-400-7,1.0,123800.0,...,2.159648e+06,97.454997,4.898459e+06,1.268174,193.137711,73.759930,119.377781,1.0,NaN,4600000007000000080010006A6900002E015801010000...

In [5]:
# 2. filter by using standard use code
surplus_land = mapc_fee_tax[ 
        (mapc_fee_tax['luc_adj_1'] == 91.0)
    | 
        ( (mapc_fee_tax['luc_adj_1'] >= 910.0) & (mapc_fee_tax['luc_adj_1'] <= 919.0) )
    |
        (mapc_fee_tax['luc_adj_1'] == 92.0)
    | 
        ( (mapc_fee_tax['luc_adj_1'] >= 920.0) & (mapc_fee_tax['luc_adj_1'] <= 929.0) ) 
    |
        (mapc_fee_tax['luc_adj_1'] == 97.0)
    | 
        ( (mapc_fee_tax['luc_adj_1'] >= 970.0) & (mapc_fee_tax['luc_adj_1'] <= 979.0) ) 
    |
        (mapc_fee_tax['luc_adj_2'] == 91.0)
    | 
        ( (mapc_fee_tax['luc_adj_2'] >= 910.0) & (mapc_fee_tax['luc_adj_2'] <= 919.0) ) 
    | 
        (mapc_fee_tax['luc_adj_2'] == 92.0)
    | 
        ( (mapc_fee_tax['luc_adj_2'] >= 920.0) & (mapc_fee_tax['luc_adj_2'] <= 929.0) ) 
    |
        (mapc_fee_tax['luc_adj_2'] == 97.0)
    | 
        ( (mapc_fee_tax['luc_adj_2'] >= 970.0) & (mapc_fee_tax['luc_adj_2'] <= 979.0) ) 
]
surplus_land

,objectid,mapc_id,muni_id,muni,parloc_id,poly_typ,map_num,mappar_id,loc_id_cnt,land_value,...,landv_pac,bldgv_psf,totv_pac,bldlnd_rat,sqm_imperv,sqm_bldg,sqm_pave,realesttyp,temp,shape
2260,1027253,1796234,165,Malden,F_782911_2980137,FEE,168,168-490-26,1.0,2160800.0,...,131282.024686,-0.999900,1.312820e+05,0.000000,3599.728666,325.967398,3273.761268,12.0,NaN,E700000021000000080010006A6900008F035801010000...
4007,1028997,1797978,165,Malden,F_781148_2981631,FEE,124,124-490-6A,1.0,15492000.0,...,257172.947956,-0.999900,2.571729e+05,0.000000,33256.783685,1129.471021,32127.312664,12.0,NaN,3C0100002F000000080010006A690000A4045801010000...
4339,1029315,1798296,165,Malden,F_768518_2982349,FEE,018,18-41-110,1.0,395100.0,...,159530.423037,-0.999900,1.595304e+05,0.000000,625.897178,-0.999900,0.000000,12.0,NaN,E200000026000000080010006A6900008A035801010000...
9799,1034744,1823813,18,Avon,F_777800_2869815,FEE,C4,C4_3_27,1.0,10300.0,...,3776.197425,-0.999900,4.945719e+04,12.097087,2848.004024,744.986183,2103.017842,12.0,NaN,5B0000000A000000080010006A69000083010A01010000...
10252,1035197,1824266,18,Avon,F_777539_2876473,FEE,C7,C7_2_1,1.0,36000.0,...,38463.124174,-0.999900,3.846312e+04,0.000000,0.347351,-0.999900,0.000000,12.0,NaN,3C00000005000000080010006A69000024010A01010000...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1272392,1022440,1776989,44,Brockton,F_788860_2847499,FEE,117,117-270,1.0,747740.0,...,161064.888824,-0.999900,1.610649e+05,0.000000,14597.749508,6.803113,14590.946395,12.0,NaN,ED00000021000000080118006A69000095032501010000...
1272407,1022455,1777004,44,Brockton,F_795045_2853182,FEE,140,140-005,1.0,18204300.0,...,192847.152786,-0.999900,5.336819e+05,1.767383,138044.877959,28386.134181,109658.743778,10.0,NaN,74040000DD000000080118006A6900009C112501010000...
1272443,1022491,1777040,44,Brockton,F_785308_2852780,FEE,63,063-123,1.0,71200.0,...,301405.210868,123.347826,9.018874e+05,1.992275,436.089852,140.864326,295.225526,12.0,NaN,4100000006000000080010006A69000029022501010000...
1272444,1022492,1777041,44,Brockton,F_785210_2852770,FEE,63,063-124,1.0,70600.0,...,336943.444035,107.429654,1.284442e+06,2.812040,396.050986,87.764146,308.286840,12.0,NaN,3C00000005000000080010006A69000024022501010000...
1272445,1022493,1777042,44,Brockton,F_785248_2852716,FEE,63,063-001,1.0,70300.0,...,373154.693479,111.006494,1.462045e+06,2.918065,665.538823,127.422037,538.116786,12.0,NaN,3C00000005000000080010006A69000024022501010000...

In [6]:
owner_names = pd.read_csv("owner_name.csv")['owner_name'].to_list()
owner_names

['WATER RESOURCES COMMISSION',
 'VET`S MEMORIAL SKATING RINK',
 'UNIVERSITY OF MASS FOUNDTION INC',
 'UNIVERSITY OF MASS BUILDING AUTHORITY',
 'UNIVERISTY OF MASS BUILDING AUTHORITY',
 'UMASS BUILDING AUTHORITY',
 'TRIAL COURT OF MASSACHUSETTS',
 'THE COMMONWEALTH OF MASSACHUSETTS',
 'THE COMMONWEALTH OF MASSACHSETTES',
 'THE COMMONWEALTH OF MASS',
 'SEWER DEPT TREATMENT PLANT',
 'Mass Bay Transportation Authority',
 'MDC/WATER DIVISION',
 'MDC AQUEDUCT',
 'MDC',
 'MCI & SECC/DEPT OF CORRECTIONS',
 'MBTA PLAN 94-690',
 'MBTA PLAN 94-687',
 'MBTA C/O REAL ESTATE ACQ.',
 'MBTA C/O REAL ESTATE',
 'MBTA - MASSACHUSETTS BAY',
 'MBTA\xa0 C/O REAL ESTATE ACQUISIT',
 'MBTA',
 'MASSPORT AUTHORITY',
 'MASSASOIT COMM COLLEGE FNDN INC',
 'MASSASOIT COMM COLLEG FNDN INC',
 'MASSACHUSETTS, COMMONWEALTH OF FORMER:MDC NOW- DCR',
 'MASSACHUSETTS, COMMONWEALTH OF FORMER MDC; NOW DCR',
 'MASSACHUSETTS, COMMONWEALTH OF DCR- FORMER MDC',
 'MASSACHUSETTS, COMMONWEALTH OF DCR',
 'MASSACHUSETTS, COMMONWEALTH OF',
 'MASSACHUSETTS, COMM. OF MDC',
 'MASSACHUSETTS, COMM. OF',
 'MASSACHUSETTS, COMM OF',
 'MASSACHUSETTS WATER',
 'MASSACHUSETTS TURNPIKE AUTHY',
 'MASSACHUSETTS TURNPIKE AUTHORITY',
 'MASSACHUSETTS TURNPIKE',
 'MASSACHUSETTS PORT AUTHORITY',
 'MASSACHUSETTS HEALTH AND\xa0 EDUCATIONAL FACILITES',
 'MASSACHUSETTS FISH & WILDLIFE',
 'MASSACHUSETTS DNR',
 'MASSACHUSETTS DEPT OF TRANSPOR',
 'MASSACHUSETTS COMMONWEALTH OF STATE FOREST',
 'MASSACHUSETTS COMMONWEALTH OF',
 'MASSACHUSETTS COMMONWEALTH',
 'MASSACHUSETTS COMMON',
 'MASSACHUSETTS COMMOMWEALTH OF',
 'MASSACHUSETTS COMM.WEALTH',
 'MASSACHUSETTS COMM OF METRO DIST COMM',
 'MASSACHUSETTS COMM OF',
 'MASSACHUSETTS COMM',
 'MASSACHUSETTS BAY TRANSPORTATION AUTHORI',
 'MASSACHUSETTS BAY TRANSPORTATION',
 'MASSACHUSETTS BAY TRANSPORTATI',
 'MASSACHUSETTS BAY TRANSPORT',
 'MASSACHUSETTS BAY TRANS AUTHORITY',
 'MASSACHUSETTS BAY TRANS AUTHOR',
 'MASSACHUSETTS BAY TRANS AUTH',
 'MASSACHUSETTS BAY TRANS',
 'MASSACHUSETTS BAY',
 'MASSACHUSETTS\xa0 BAY',
 'MASSACHUSETTS',
 'MASS. HIGHWAY',
 'MASS, COMMONWEALTH OF',
 'MASS WATER RESOURCES AUTHORITY',
 'MASS WATER RESOURCES AUTH',
 'MASS TURNPIKE AUTHORITY',
 'MASS TURNPIKE',
 'MASS STATE COLLEGE BLDG AUTHORITY',
 'MASS HIGHWAY DEPT',
 'MASS DEPT OF TRANSPORTATION',
 'MASS DEPT OF PUBLIC WORKS',
 'MASS DEPT OF HIGHWAYS',
 'MASS DEPT OF FISHERIES',
 'MASS DEPARTMENT OF TRANSPORTATION',
 'MASS COMMONWEALTH OF DEPT',
 'MASS COMMONWEALTH OF',
 'MASS COMM OF TRUSTEES',
 'MASS COMM OF',
 'MASS BAY TRANSPORTION AUTHORITY',
 'MASS BAY TRANSPORTATION AUTHORITY',
 'MASS BAY TRANSPORTATION AUTHOR',
 'MASS BAY TRANSPORTATION AUTH.',
 'MASS BAY TRANSPORTATION AUTH',
 'MASS BAY TRANSPORTATION AUT',
 'MASS BAY TRANSPORTATION',
 'MASS BAY TRANSPORATION AUTHORITY',
 'MASS BAY TRANSP AUTHORITY',
 'MASS BAY TRANSIT AUTHORITY',
 'MASS BAY TRANSIT AUTH',
 'MASS BAY TRANS. AUTHORITY',
 'MASS BAY TRANS AUTHORITY',
 'MASS BAY TRANS AUTH',
 'MASS BAY TRAN AUTHORITY',
 'MASS ABY TRANSPORATION AUTHORITY',
 'MASS\xa0 BAY TRANSPORTATION AUTH.',
 'MASS\xa0 BAY TRANS AUTHORITY',
 'MA/DCR',
 'MA DEPT OF TRANSPORTATION',
 'M.W.R.A.',
 'M.D.C.',
 'M.B.T.A.',
 'M D C',
 'M BAY TRANS AUTHORITY',
 'M BAY TRAN AUTHORITY',
 'M B T A',
 'HEALTH & EDUCATIONAL FACILITIES AUTHORIT',
 'HEALTH & EDUCATION FACILITIES AUTHORITY',
 'Dept. of Consv. and Recreation',
 'DIVISION OF FISHERIES + GAME',
 'DIVISION OF FISHERIES & WILDLIFE',
 'DIV OF FISHERIES & GAME',
 'DEPT/CONSERVATION & RECREATION',
 'DEPT. OF CONSERVATION AND RECREATION',
 'DEPT. OF CONSERVATION & RECREATION',
 'DEPT OR CONSERVATION & RECREATION',
 'DEPT OF PUBLIC WORKS',
 'DEPT OF ENVIRONMENTAL MGMT',
 'DEPT OF ENVIRONMENTAL MANAGEMENT',
 'DEPT OF ENVIR MANAGEMENT',
 'DEPT OF CONSERVATION AND RECREATION',
 'DEPT OF CONSERVATION AND REC.',
 'DEPT OF CONSERVATION & RECREATION',
 'DEPT OF CONSERVATION & RECREAT',
 'DEPT OF CONSERVATION & REC',
 'DEPT OF CONSERV AND REC',
 'DEPT ENVIR MANAGEMENT',
 'DEPT 0F CONSERVATION & REC',
 'DEPARTMENT OF PUBLIC WORKS',
 'DEPARTMENT OF FISHERIES &',
 'DEPARTMENT OF FISH AND GAME',
 'DEPARTMENT OF CONSERVATION AND RECREATION',
 'DEPARMENT OF FISHERIES &',
 'Commonwealth of Massachusetts',
 'COMMWEALTH OF MASSACHUSETTS',
 'COMMONWELTH OF MASSACHUSETTS\xa0 THE',
 'COMMONWEATH OF, MASS DIST #4',
 'COMMONWEATH OF, MASS',
 'COMMONWEATH OF MASSACHUSETTS',
 'COMMONWEATH OF MASS',
 'COMMONWEALTH OF MASSCHUSETTS',
 'COMMONWEALTH OF MASSACHUSETTS,RAIL TRAIL',
 'COMMONWEALTH OF MASSACHUSETTS, MBTA',
 'COMMONWEALTH OF MASSACHUSETTS, DIVISION',
 'COMMONWEALTH OF MASSACHUSETTS EGG ROCK',
 'COMMONWEALTH OF MASSACHUSETTS',
 'COMMONWEALTH OF MASSACHUSETT',
 'COMMONWEALTH OF MASSACHUSET',
 'COMMONWEALTH OF MASS/STATE HIGHWAY',
 'COMMONWEALTH OF MASS/DPW',
 'COMMONWEALTH OF MASS/DOT',
 'COMMONWEALTH OF MASS/DCR',
 'COMMONWEALTH OF MASS.',
 'COMMONWEALTH OF MASS, DEPT OF CONSERVATION & RECRE',
 'COMMONWEALTH OF MASS HIGHWAY',
 'COMMONWEALTH OF MASS ENV MGT AND DEPT OF NATURAL RESOURCES',
 'COMMONWEALTH OF MASS ENV MGT AND DEPT OF FOREST AN',
 'COMMONWEALTH OF MASS DPW',
 'COMMONWEALTH OF MASS DOT',
 'COMMONWEALTH OF MASS DIV OF CAPT AS MNGE',
 'COMMONWEALTH OF MASS DIST #4',
 'COMMONWEALTH OF MASS DEPT OF P',
 'COMMONWEALTH OF MASS DEPT OF N ATURAL RESOURCES',
 'COMMONWEALTH OF MASS DEPT OF',
 'COMMONWEALTH OF MASS DEPT ENVIRONMENTAL MGT',
 'COMMONWEALTH OF MASS AND SUPT OF ARMORIES',
 'COMMONWEALTH OF MASS AND MBTA',
 'COMMONWEALTH OF MASS - MDC',
 'COMMONWEALTH OF MASS (DEPT OF\xa0 NATURAL RES.)',
 'COMMONWEALTH OF MASS\xa0 MDR',
 'COMMONWEALTH OF MASS\xa0 DMR',
 'COMMONWEALTH OF MASS \xa0 DMR',
 'COMMONWEALTH OF MASS',
 'COMMONWEALTH OF MA HWY',
 'COMMONWEALTH OF MA DEPT PUBLIC SAFETY',
 'COMMONWEALTH OF MA - DPW',
 'COMMONWEALTH OF MA',
 'COMMONWEALTH OF\xa0 MASSACHUSETTS',
 'COMMONWEALTH OF\xa0 MASS',
 'COMMONWEALTH\xa0 OF\xa0 MASSACHUSETTS',
 'COMMOMWEALTH OF MASS',
 'COMM. OF MASSACHUSETTS',
 'COMM.\xa0 OF MASS\xa0 MDC, DEPT OF CONSERVATION & RECREA',
 'COMM OF MASSACUSETTS',
 'COMM OF MASSACHUSETTS',
 'COMM OF MASS/STATE POLICE',
 'COMM OF MASS/DIV OF FISHERIES',
 'COMM OF MASS/DIV FISHERIES',
 'COMM OF MASS/DIV\xa0 FISHERIES',
 'COMM OF MASS/ DIV FISHERIES',
 'COMM OF MASS-HIGHWAY DEPT.',
 'COMM OF MASS-DEPT OF ENV MGMT',
 'COMM OF MASS,MDC',
 'COMM OF MASS,FLOOD CONTROL',
 'COMM OF MASS,ARMORY',
 'COMM OF MASS MET DIST COMM',
 'COMM OF MASS MDC',
 'COMM OF MASS FISH + GAME',
 'COMM OF MASS DIV FISHERIES & WILDLIFE',
 'COMM OF MASS DEPT OF PUBLIC WORKS',
 'COMM OF MASS DEPT OF HIGHWAYS',
 'COMM OF MASS DEPT MENTAL HEALT',
 'COMM OF MASS DEM',
 'COMM OF MASS CAMPCURTIS GUILD',
 'COMM OF MASS -MDC',
 'COMM OF MASS - TPKE',
 'COMM OF MASS - N/F METRO WATER DIST COMM',
 'COMM OF MASS - MDC',
 'COMM OF MASS (M.D.C.)',
 'COMM OF MASS',
 'COMM OF MA ON BEHALF OF',
 'COMM OF MA FISHERIES WILDLIFE',
 'COMM OF MA DIV OF CAPTL ASSET',
 'COMM OF MA DIV OF CAP ASSET',
 'COM OF MASS DEPT FISHERIES, WILDLIFE & E',
 'COM OF MASS DCAM - DCR',
 'COM OF MASS',
 '""MASS BAY',
 '""COMM OF MASS']

In [7]:
# 3. filter by owner_name to get state owned parcels
state_owned_surplus_land = surplus_land[surplus_land['owner_name'].isin(owner_names)]
state_owned_surplus_land

,objectid,mapc_id,muni_id,muni,parloc_id,poly_typ,map_num,mappar_id,loc_id_cnt,land_value,...,landv_pac,bldgv_psf,totv_pac,bldlnd_rat,sqm_imperv,sqm_bldg,sqm_pave,realesttyp,temp,shape
9799,1034744,1823813,18,Avon,F_777800_2869815,FEE,C4,C4_3_27,1.0,10300.0,...,3776.197425,-0.9999,49457.187633,12.097087,2848.004024,744.986183,2103.017842,12.0,NaN,5B0000000A000000080010006A69000083010A01010000...
12648,1037600,1838458,38,Boxford,M_240411_939010,FEE,15,15-2-8.2,1.0,262100.0,...,106499.249430,-0.9999,106499.249430,0.000000,-0.999900,-0.999900,0.000000,12.0,NaN,600000000B000000080010006A69000088010A01010000...
12913,1037859,1838718,38,Boxford,M_241128_933069,FEE,36,36-1-4,1.0,75700.0,...,8965.896814,-0.9999,8965.896814,0.000000,-0.999900,-0.999900,0.000000,12.0,NaN,AC00000017000000080010006A69000094020A01010000...
12923,1037867,1838726,38,Boxford,M_241410_932643,FEE,37,37-1-1,1.0,2904300.0,...,56105.299188,-0.9999,56105.299188,0.000000,1361.338878,-0.999900,0.000000,12.0,NaN,FF01000053000000080010006A690000A7070A01010000...
12936,1037881,1838740,38,Boxford,M_242988_935969,FEE,26,26-2-2.1,1.0,12800.0,...,11537.736793,-0.9999,11537.736793,0.000000,-0.999900,-0.999900,0.000000,12.0,NaN,5F0000000B000000080010006A69000087010A01010000...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1270684,1020732,1775281,44,Brockton,F_792288_2866114,FEE,174,174-206,1.0,300.0,...,65778.684185,-0.9999,65778.684185,0.000000,11.374276,-0.999900,0.000000,12.0,NaN,3800000005000000080010006A69000020012501010000...
1271322,1021369,1775918,44,Brockton,F_797400_2866819,FEE,177,177-020,1.0,17800.0,...,11634.486758,-0.9999,11634.486758,0.000000,-0.999900,-0.999900,0.000000,12.0,NaN,A200000018000000080010006A6900008A022501010000...
1271854,1021917,1776466,44,Brockton,F_791707_2868935,FEE,179,179-438,1.0,700.0,...,21935.927623,-0.9999,21935.927623,0.000000,75.963646,-0.999900,0.000000,12.0,NaN,4200000006000000080010006A6900002A022501010000...
1272115,1022163,1776712,44,Brockton,F_790839_2869784,FEE,179,179-239,1.0,500.0,...,21439.409034,-0.9999,21439.409034,0.000000,1.930091,-0.999900,0.000000,12.0,NaN,3600000004000000080010006A6900001E022501010000...
1272392,1022440,1776989,44,Brockton,F_788860_2847499,FEE,117,117-270,1.0,747740.0,...,161064.888824,-0.9999,161064.888824,0.000000,14597.749508,6.803113,14590.946395,12.0,NaN,ED00000021000000080118006A69000095032501010000...

In [8]:
state_owned_surplus_land.to_csv("state_owned_surplus_land.csv")

In [10]:
pd.set_option('display.float_format',lambda x : '%.2f' % x)

In [11]:
state_owned_surplus_land.sum()

objectid                                              2926458285
mapc_id                                               5221551392
muni_id                                                   841910
muni           AvonBoxfordBoxfordBoxfordBoxfordBoxfordBoxford...
parloc_id      F_777800_2869815M_240411_939010M_241128_933069...
poly_typ       FEEFEEFEEFEEFEEFEEFEEFEEFEEFEEFEEFEEFEEFEEFEEF...
loc_id_cnt                                               4786.00
land_value                                         3010508287.00
bldg_value                                         2397043680.00
othr_value                                          201161780.00
total_value                                        5614742787.00
ls_price                                           1556917090.00
bldg_area                                            15746991.00
res_area                                             11975920.00
luc_adj_1                                             4346855.00
luc_adj_2                                             4358052.00
num_units                                              717693.00
units_est                                              722302.00
units_src      loc_idcnloc_idcnloc_idcnloc_idcnloc_idcnloc_id...
num_rooms                                                 624.00
yr_built                                               845206.00
owner_name     MASSACHUSETTS COMMONWEALTH OFCOMMONWEALTH OF M...
fy                                                    9501683.00
lot_areaft                                         3631494486.26
far                                                       202.04
pct_imperv                                              79721.92
pct_bldg                                                10497.67
pct_pave                                                34902.64
landv_pac                                          2041542994.62
bldgv_psf                                            89967042.04
totv_pac                                          33823535875.14
bldlnd_rat                                               3736.09
sqm_imperv                                           12714555.10
sqm_bldg                                              1530943.04
sqm_pave                                              8609544.78
realesttyp                                              55920.00
temp                                                     4880.02
shape          5B0000000A000000080010006A69000083010A01010000...
dtype: object